### ISSUE TITLE
no output

### ISSUE THREAD

**Issue by broadwit** [ACassimiro/TSNsched#22]
Hi,

I have all dependencies installed successfully by running "sudo ./install-dependencies.sh".

But, after running the following commands, 
cd ./Script
./generateSchedule.sh example.java

It display the following text:
:./libs/com.microsoft.z3.jar:./libs/gson-2.8.6.jar:./libs/java-json.jar:./libs/TSNsched.jar
mv: cannot stat 'log.txt': No such file or directory
Ending execution

and Script/output/example.java.out is empty.

Can you help me?

**Comment by broadwit** [comment]
My OS is ubuntu 18.04

**Comment by 844651975** [comment]
me too

**Comment by nihaoa56** [comment]
the same problem,too.

**Comment by ACassimiro** [comment]
Hello,

Due to some changes performed while implementing the json input mode for TSNsched, some of the workflow for topologies specified in java code were changed.

I've just fixed the bugs that caused your issue. Notice that on the example file (Script/example.java) you now have to make explicit that you want to enable your console output and logging (lines 451 and 452, added in the commit 5431d33).

Please, update your version of TSNsched and try again. Let me know if you run into any other issues.
