### ISSUE TITLE
generateSchedule.sh example.java

### ISSUE THREAD

**Issue by ghjk138243** [ACassimiro/TSNsched#25]
![10](https://user-images.githubusercontent.com/103174038/169265475-a0140715-c841-420f-82f3-6ca0b4b4c9d1.PNG)
how can i solve this issue

**Comment by ACassimiro** [comment]
I believe that this might have something to do with a patch that I implemented in TSNsched to make it work in new M1 mac processors, which I'm currently using to work in my projects. I'll be going to investigate it and should push a fix for it in the next few days. For now, this can be fixed by reverting my last commit, as mentioned in this git issue #24 . Feel free to reopen this issue if this solution doesn't work for you.
